CREATE TABLE families
(
    id     BIGINT       NOT NULL GENERATED by default as identity PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    userId BIGINT       NOT NULL,
    CONSTRAINT FK_families_users_user_id_id FOREIGN KEY (userId) REFERENCES users (id),
    CONSTRAINT UQ_families_name_userId UNIQUE (name, userId)
);
