CREATE TABLE family_members
(
    id           BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId       BIGINT                      NOT NULL,
    familyId     BIGINT                      NOT NULL,
    requestDate  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validTo      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 days',
    approved     BOOLEAN                     NOT NULL DEFAULT FALSE,
    approvedDate TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT FK_familyMembers_users_user_id_id FOREIGN KEY (userId) REFERENCES users (id),
    CONSTRAINT FK_familyMembers_families_family_id_id FOREIGN KEY (familyId) REFERENCES families (id)
);
