CREATE TABLE locations
(
    id             BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                      NOT NULL,
    family_member_id BIGINT                      NOT NULL,
    latitude       DOUBLE PRECISION            NOT NULL,
    longitude      DOUBLE PRECISION            NOT NULL,
    report_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_locations_users_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT FK_locations_families_family_member_id FOREIGN KEY (family_member_id) REFERENCES family_members(id),
);
