CREATE TABLE users (
    id bigint not null generated by default as identity primary key ,
    username varchar(50) not null unique,
    password varchar(255) not null,
    email varchar(50) not null unique,
    name varchar(50) not null,
    surname varchar(50) not null,
    birthdate date null,
    gender char(1) null,
    role_id int not null,
    constraint fk_users_role_role_id foreign key (role_id) references roles(id)
);